agora/cerebral_api/Dockerfile, agora/cerebral_api/InfluxDBHandler.py, agora/cerebral_api/app.py, agora/cerebral_api/llm.py, agora/cerebral_api/main.py, agora/cerebral_api/operations/cerebral-api.yaml, agora/cerebral_api/operations/cerebral-simulator.yaml, agora/cerebral_api/operations/influxdb-setup.yaml, agora/cerebral_api/operations/influxdb.yaml, agora/cerebral_api/operations/mssql-setup.yaml, agora/cerebral_api/operations/mssql.yaml
Includes the initial version of the Cerebral API, and the folder with operations with all the prerequisites.
=> Cerebral - Initial code version

agora/intrusion_detection/app.py, agora/intrusion_detection/requirements.txt, agora/intrusion_detection/static/js/main.js, agora/intrusion_detection/templates/index.html
First release for Intrusion detection - WIP
=> Docker-compose

agora/intrusion_detection_api/src/app.py, agora/intrusion_detection_api/src/static/js/main.js, agora/intrusion_detection_api/src/templates/index.html
New release with multiple ailes detection and extended analytics. Code base merged with the changes Francisco did for React.
=> Multiple aisles detection and visitor analytics

agora/footfall_ai_api/src/app.py, agora/footfall_ai_api/src/templates/index.html, agora/footfall_ai_api/src/video_capture.py, agora/footfall_ai_api/src/video_processor.py, agora/intrusion_detection_api/src/app.py
- Added support for multiple cameras
- Each camera has its own context and data
- 1 Thread per camera with (1 thread for processing and 1 thread for capturing)
- Updated Index.html for testing multi-camera
=> Multi camera fixer

agora/genie_simulator/src/app.py
The following metrics were added for Prometheus:
- Refrigerator
- Scale
- POS
- SmartShelf
- HVAC
- LightingSystem
- AutomatedCheckout
=> Genie - Addition of new metrics for Prometheus and Grafana

agora/genie_simulator/src/app.py
Corrected problem with the LIGHTING metric that caused it to stop working after a while
=> Corrected problem with lights and optimized code (DRY)

agora/contoso_hypermarket/README.md, agora/footfall_ai_api/operations/footfall.yaml, agora/genie_api/operations/influxdb.yaml, agora/main_ui/operations/rtsp.yaml, agora/shopper_experience_api/operations/shopper-experience.yaml
Update manifests with real download links and fix a few issues. Add shopper-experience to readme
=> update with new download links

.gitignore, agora/contoso_hypermarket/docker-compose-rtsp.yml, agora/shopper_experience_api/src/video_capture.py, agora/shopper_experience_api/src/video_processor.py
- Add new model for age and gender
- Added insights for new model
=> Shopper insights

agora/shopper_experience_api/src/app.py, agora/shopper_experience_api/src/prometheus_metrics.py, agora/shopper_experience_api/src/video_processor.py
- Remove all gender references of code
- Remove gender inferencing
- Created Prometheus collector
- Created /metrics endpoint for prometheus
=> Remove gender and add Prometheus endpoint

agora/contoso_hypermarket/charts/agora-ui/.helmignore, agora/contoso_hypermarket/charts/agora-ui/Chart.yaml, agora/contoso_hypermarket/charts/agora-ui/templates/NOTES.txt, agora/contoso_hypermarket/charts/agora-ui/templates/_helpers.tpl, agora/contoso_hypermarket/charts/agora-ui/templates/deployment.yaml, agora/contoso_hypermarket/charts/agora-ui/templates/service.yaml, agora/contoso_hypermarket/charts/agora-ui/values.yaml, agora/contoso_hypermarket/charts/contoso-hypermarket/.helmignore, agora/contoso_hypermarket/charts/contoso-hypermarket/Chart.lock, agora/contoso_hypermarket/charts/contoso-hypermarket/Chart.yaml, agora/contoso_hypermarket/charts/contoso-hypermarket/templates/NOTES.txt, agora/contoso_hypermarket/charts/contoso-hypermarket/values.yaml, agora/contoso_hypermarket/charts/rtsp/.helmignore, agora/contoso_hypermarket/charts/rtsp/Chart.yaml, agora/contoso_hypermarket/charts/rtsp/templates/NOTES.txt, agora/contoso_hypermarket/charts/rtsp/templates/_helpers.tpl, agora/contoso_hypermarket/charts/rtsp/templates/deployment.yaml, agora/contoso_hypermarket/charts/rtsp/templates/pvc.yaml, agora/contoso_hypermarket/charts/rtsp/templates/service.yaml, agora/contoso_hypermarket/charts/rtsp/values.yaml
- intial Helm charts for main_ui and RTSP
=> initial Helm charts

agora/shopper_insights_api/src/prometheus_metrics.py
- Add metrics for avg seconds
- Fix issues when setting the detection area
=> Fix for shopper insights metrics

agora/footfall_ai_api/src/app.py, agora/shopper_insights_api/src/app.py
- Identify cameras by name and not by video_url
- Update cameras configuration when refreshing
- Update /status endpoint for multiple camera status
=> Footfall ai metrics

agora/contoso_hypermarket/charts/rtsp/templates/deployment.yaml, agora/contoso_hypermarket/charts/rtsp/templates/service.yaml, agora/contoso_hypermarket/charts/rtsp/values.yaml
this PR adds the zoom and aisle RTSP feeds
=> PR - add zoom and aisle to RTSP

agora/footfall_ai_api/src/app.py, agora/footfall_ai_api/src/requirements.txt
- Added CORS for integration with Main UI
- Added TS to /Status endpoint
=> Footfall API - CORS and TS

.gitignore, agora/cerebral_rag/src/dockerfile
- Added .pdf extension in the gitignore
- Container download manuals from repository
=> Download of the documents (OT Manuals)

agora/contoso_hypermarket/charts/main-ui-backend-db/.helmignore, agora/contoso_hypermarket/charts/main-ui-backend-db/Chart.yaml, agora/contoso_hypermarket/charts/main-ui-backend-db/templates/NOTES.txt, agora/contoso_hypermarket/charts/main-ui-backend-db/templates/_helpers.tpl, agora/contoso_hypermarket/charts/main-ui-backend-db/templates/configmap.yaml, agora/contoso_hypermarket/charts/main-ui-backend-db/templates/deployment.yaml, agora/contoso_hypermarket/charts/main-ui-backend-db/templates/pvc.yaml, agora/contoso_hypermarket/charts/main-ui-backend-db/templates/service.yaml, agora/contoso_hypermarket/charts/main-ui-backend-db/values.yaml
this is the initial chart to deploy the Main UI Backend DB
=> initial chart for UI backend DB

agora/contoso_hypermarket/charts/rtsp/templates/deployment.yaml
this PR updates the filenames for the mp4 to aisle and zoom for the respective service to fix the sample file from being overwritten
=> update aisle and zoom filenames

agora/main_ui/src/src/components/WizardNavigationStatus.tsx, agora/main_ui/src/src/pages/cameraszoneswizardsetupcamera/index.tsx, agora/main_ui/src/src/pages/camerazoneswizard/index.tsx, agora/main_ui/src/src/pages/camerazoneswizardfloor/index.tsx, agora/main_ui/src/src/pages/camerazoneswizardreview/index.tsx
Completed wizard navigation control for the camera zone wizard.
=> Completed wizard navigation control for the camera zone wizard.

agora/contoso_hypermarket/charts/agora-ui/values.yaml
This PR updates the agora-ui chart to use the UI stored in MCR
=> use MCR for agora_ui

agora/contoso_hypermarket/charts/contoso-hypermarket/Chart.yaml, agora/contoso_hypermarket/charts/footfall-ai-api/.helmignore, agora/contoso_hypermarket/charts/footfall-ai-api/Chart.yaml, agora/contoso_hypermarket/charts/footfall-ai-api/templates/NOTES.txt, agora/contoso_hypermarket/charts/footfall-ai-api/templates/_helpers.tpl, agora/contoso_hypermarket/charts/footfall-ai-api/templates/deployment.yaml, agora/contoso_hypermarket/charts/footfall-ai-api/templates/pvc.yaml, agora/contoso_hypermarket/charts/footfall-ai-api/templates/service.yaml, agora/contoso_hypermarket/charts/footfall-ai-api/values.yaml
this PR adds the Footfall API as a Helm chart and adds the main-ui-backend-api, main-ui-backend-db, and footfall to the overarching contoso-hypermarket chart
=> Helm footfall api

agora/contoso_hypermarket/charts/main-ui-backend-api/.helmignore, agora/contoso_hypermarket/charts/main-ui-backend-api/Chart.yaml, agora/contoso_hypermarket/charts/main-ui-backend-api/templates/NOTES.txt, agora/contoso_hypermarket/charts/main-ui-backend-api/templates/_helpers.tpl, agora/contoso_hypermarket/charts/main-ui-backend-api/templates/deployment.yaml, agora/contoso_hypermarket/charts/main-ui-backend-api/templates/service.yaml, agora/contoso_hypermarket/charts/main-ui-backend-api/values.yaml
this is the initial main-ui-backend-api chart
=> initial main-ui-backend-api chart

agora/contoso_hypermarket/charts/influxdb/Chart.yaml, agora/contoso_hypermarket/charts/influxdb/templates/NOTES.txt, agora/contoso_hypermarket/charts/influxdb/templates/_helpers.tpl, agora/contoso_hypermarket/charts/influxdb/templates/influxdb-setup.yaml, agora/contoso_hypermarket/charts/influxdb/templates/influxdb.yaml, agora/contoso_hypermarket/charts/influxdb/values.yaml
This is the initial InfluxDB chart.  Unlike what was done for contoso-motors, this does NOT deploy pre-configured dashboards.  If that needs to be added I'll submit another PR.  Additionally, the Values file is set to use the influxdb image from the MCR.
=> initial InfluxDB chart

agora/contoso_hypermarket/README.md, agora/contoso_hypermarket/charts/cerebral-api/.helmignore, agora/contoso_hypermarket/charts/cerebral-api/Chart.yaml, agora/contoso_hypermarket/charts/cerebral-api/templates/cerebral-api.yaml, agora/contoso_hypermarket/charts/cerebral-api/templates/cerebral-chroma.yaml, agora/contoso_hypermarket/charts/cerebral-api/templates/cerebral-simulator.yaml, agora/contoso_hypermarket/charts/cerebral-api/templates/mssql-setup.yaml, agora/contoso_hypermarket/charts/cerebral-api/templates/mssql.yaml, agora/contoso_hypermarket/charts/cerebral-api/values.yaml
this is the initial Helm chart for the cerebral-api.  For now, I omitted the cerebral-simulator-prometheus.yaml manifest because we'll have to have the prom stack deployed first and I want to first have the basic contoso-hypermarket set of charts working.  In addition, there are a number of hardcoded endpoints (unchanged from the original manifest) that we'll have to talk through how we handle those, like AZURE_OPENAI_ENDPOINT, REDIS_URL, etc.
=> Helm Chart: initial cerebral-api chart

agora/contoso_hypermarket/charts/shopper-insights/.helmignore, agora/contoso_hypermarket/charts/shopper-insights/Chart.yaml, agora/contoso_hypermarket/charts/shopper-insights/templates/NOTES.txt, agora/contoso_hypermarket/charts/shopper-insights/templates/_helpers.tpl, agora/contoso_hypermarket/charts/shopper-insights/templates/deployment.yaml, agora/contoso_hypermarket/charts/shopper-insights/templates/pvc.yaml, agora/contoso_hypermarket/charts/shopper-insights/templates/service.yaml, agora/contoso_hypermarket/charts/shopper-insights/values.yaml
this is the initial chart for shopper-insights.  It currently omits the ServiceMonitor for Prometheus, as we'll need to have the prom stack deployed first and I wanted to get the basic shopper-insights chart deployed.
=> Helm - shopper insights

agora/cerebral_api/operations/cerebral-simulator.yaml, agora/contoso_hypermarket/charts/cerebral-api/templates/cerebral-simulator.yaml
this fixes the issue with quoting on the additional environment parameters in the cerebral simulator
=> add quotes for values

agora/contoso_hypermarket/charts/agora-ui/templates/deployment.yaml, agora/contoso_hypermarket/charts/agora-ui/values.yaml, agora/contoso_hypermarket/charts/cerebral-api/templates/cerebral-api.yaml, agora/contoso_hypermarket/charts/cerebral-api/values.yaml, agora/contoso_hypermarket/charts/footfall-ai-api/templates/deployment.yaml, agora/contoso_hypermarket/charts/footfall-ai-api/values.yaml, agora/contoso_hypermarket/charts/influxdb/templates/influxdb.yaml, agora/contoso_hypermarket/charts/influxdb/values.yaml, agora/contoso_hypermarket/charts/main-ui-backend-api/templates/deployment.yaml, agora/contoso_hypermarket/charts/main-ui-backend-api/values.yaml, agora/contoso_hypermarket/charts/main-ui-backend-db/templates/deployment.yaml, agora/contoso_hypermarket/charts/main-ui-backend-db/values.yaml, agora/contoso_hypermarket/charts/rtsp/values.yaml, agora/contoso_hypermarket/charts/shopper-insights/templates/deployment.yaml, agora/contoso_hypermarket/charts/shopper-insights/values.yaml
change pull policy to always pull so we ensure we use the newest images from MCR
=> update imagePullPolicy to Always

agora/footfall_ai_api/src/app.py, agora/footfall_ai_api/src/video_processor.py
- Print model being used (Yolov8 or Yolov5)
- Remove unused imports
=> Minor model print for model selection

agora/cerebral_simulator/src/app.py, agora/cerebral_simulator/src/store_simulator.py
- Add POS_FAILURE Counter in Prometheus
- Implement 5 failure types for POS devices
- Add /api/v1/pos/failures endpoint
- Add failure monitoring in device simulation
- Update Swagger documentation
=> Add POS failure monitoring and metrics

agora/cerebral_simulator/src/app.py, agora/cerebral_simulator/src/store_simulator.py
Now disabling writing to InfluxDb does not cause container failures.
=> Improved InfluxDB write disabling

agora/contoso_hypermarket/charts/cerebral-api/templates/mssql-setup.yaml
=> fix with Armando's SQL script

agora/cerebral_api/operations/cerebral-simulator.yaml, agora/cerebral_api/src/Dockerfile, agora/contoso_hypermarket/charts/cerebral-api/templates/cerebral-simulator.yaml
- added the STORE_ID parameter as a parameter in the helm chart
=> STORE_ID added in helm chart

agora/cerebral_simulator/src/app.py, agora/cerebral_simulator/src/store_simulator.py
- Add independent service initialization and error handling
- Service independence (SQL, MQTT, Influx DB, EventHub) now operate independently  
- Implement automatic service recovery
- Add graceful degradation for unavailable services
- Improve resource management and cleanup
- Add better configuration validation and logging
=> Add service resilience and error handling

agora/contoso_hypermarket/charts/rtsp/templates/deployment.yaml, agora/main_ui/operations/rtsp.yaml
Reupload new versions of the videos, as they had some issues when playing with the RTSP simulators due to corrupted metadata
=> Adding fixed mp4s

agora/main_ui/src/src/components/Cards.tsx, agora/main_ui/src/src/components/MaintenanceMenu.tsx, agora/main_ui/src/src/components/SideMenu.tsx
Wired up the automatedCheckoutsOpen API to populate the top cards for storemanager and maintenance worker dashboard. Fixed side menu behavior.
=> Wired up the automatedCheckoutsOpen API to populate the top cards for storemanager and maintenance worker dashboard. Fixed side menu behavior

agora/cerebral_simulator/src/app.py, agora/cerebral_simulator/src/store_simulator.py
- Optimized parallel execution of the simulator for enhanced performance and efficiency in data generation.
- Added `product_name` field to the inventory endpoint (`/api/v1/inventory`) and the inventory summary endpoint (`/api/v1/inventory/summary`) to provide more detailed product information in each API response.
=> Improvements in simulator parallel execution and addition of `product_name` to inventory API

agora/shopper_insights_api/src/app.py, agora/shopper_insights_api/src/prometheus_metrics.py, agora/shopper_insights_api/src/static/js/main.js, agora/shopper_insights_api/src/video_processor.py
- Fixed Prometheus metrics
- Change metrics ID for camera_name instead of URL
=> Fixes for better prometheus metrics

agora/main_ui/src/src/components/MaintenanceZones.tsx, agora/main_ui/src/src/components/MaintenanceZonesGrid.tsx
Zones grid wiring up with API checked in.
=> Zones grid wiring up with API checked in.

agora/contoso_hypermarket/contoso-hypermarket-helm-release.yaml
increase HelmRelease timeout time to 20m and interval to 10m to allow more time for SLM, etc. to be pulled down to cluster
=> increase timeout time to 20m

.gitignore, agora/contoso_hypermarket/charts/main-ui-backend-api/templates/deployment.yaml, agora/shopper_insights_api/operations/shopper-insights-trigger.yaml, agora/shopper_insights_api/src/app.py, agora/shopper_insights_api/src/prometheus_metrics.py
- Create new job to trigger shopper insights inferencing flow
- Fixed Grafana metrics
-
=> Trigger Shopper insights

agora/contoso_hypermarket/charts/cerebral-api/templates/cerebral-api.yaml, agora/contoso_hypermarket/charts/cerebral-api/templates/cerebral-simulator.yaml, agora/contoso_hypermarket/charts/cerebral-api/templates/mssql-setup.yaml, agora/contoso_hypermarket/charts/cerebral-api/templates/mssql.yaml
this PR updates the cerebral-api, cerebral-simulator, and mssql to use Kubernetes secrets.
=> Helm - Pull Endpoints and Keys from Kubernetes Secrets

agora/main_ui/src/src/pages/cameraszones/index.tsx, agora/main_ui/src/src/pages/cameraszoneswizardsetupcamera/index.tsx, agora/main_ui/src/src/pages/camerazoneswizard/index.tsx, agora/main_ui/src/src/pages/camerazoneswizardfloor/index.tsx, agora/main_ui/src/src/pages/camerazoneswizardreview/index.tsx, agora/main_ui/src/src/pages/inventorydashboard/index.tsx, agora/main_ui/src/src/pages/maintenanceworker/index.tsx, agora/main_ui/src/src/pages/maintenanceworkerdashboard/index.tsx, agora/main_ui/src/src/pages/shopper/index.tsx, agora/main_ui/src/src/pages/shopperproductdetail/index.tsx, agora/main_ui/src/src/pages/shopperproducts/index.tsx, agora/main_ui/src/src/pages/shopperreviewcart/index.tsx
Checking in code to fix the close icon not being displayed on the Cerebral and other panels.
=> Checking in code to fix the close icon not being displayed on the Cerebral and other panels

agora/contoso_hypermarket/charts/cerebral-api/templates/cerebral-api.yaml, agora/contoso_hypermarket/docker-compose/docker-compose-cerebral.yml
- Fix docker compose
- Fix helm chart for new secret literal
=> Fix for helm API Version

agora/main_ui/src/src/components/Cameras.tsx, agora/main_ui/src/src/components/MaintenanceCameras.tsx, agora/main_ui/src/src/components/MaintenanceZones.tsx, agora/main_ui/src/src/components/ShopperTopNav.tsx, agora/main_ui/src/src/pages/camerazoneswizard/index.tsx, agora/main_ui/src/src/pages/inventorydashboard/index.tsx
Added code to comment out components that are not functional yet. Once we are ready to add functionality to the commented-out components, we will uncomment the check in code. The commented-out components include:
- Top dropdowns on the shopper screens.
- Search and sort by drop down on maintenance worker pages and store manage pages.
- Disabling of the browse button on the upload floor plan.
=> Added code to comment out components that are not functional yet.

agora/main_ui/src/src/components/MaintenanceCards.tsx, agora/main_ui/src/src/components/MaintenanceWorkerHeader.tsx, agora/main_ui/src/src/components/MaintenanceZonesGrid.tsx, agora/main_ui/src/src/components/ShopperHeader.tsx, agora/main_ui/src/src/components/SuiteHeader.tsx
Main UI fixes for pointing logo links to homepage, commenting out of "Learn more" and camera names hyperlinks and fixing of shopper header.
=> Main UI fixes for pointing logo links to homepage, commenting out of "Learn more" and camera names hyperlinks and fixing of shopper header.

agora/contoso_motors/charts/flask-app/templates/contoso-motors-webapp.yaml, agora/contoso_motors/charts/mqtt/templates/mqtt-listener.yaml, agora/contoso_motors/charts/mqtt/templates/mqtt_simulator.yaml, agora/contoso_motors/charts/opc-simulator/values.yaml
this updates Contoso Motors images to use the MCR
=> use MCR for images

agora/contoso_hypermarket/charts/rtsp/templates/deployment.yaml
This PR fixes the RTSP for Hypermarket to show zoom and aisle instead of the Motors RTSP feeds
=> Contoso Hypermarket - fix RTSP feeds
